// import vitePluginSeoPrerender from "vite-plugin-seo-prerender";


import seoPrerender from "vite-plugin-seo-prerender";

export function seoperender(){
    return seoPrerender({
        routes: [
            '/',
            '/timetran',
            '/md5',
            '/json',
            '/reg',
            '/unicode',
            '/wordcount',
            '/scaletran',
            '/signimage',
            '/randompassword',
            '/urlencode',
            '/ascii',
            '/uuid',
            '/barrage',
            '/unit',
            '/qrcode',
            '/decision',
            '/morse',
            '/random',
            '/numbertochinese',
            '/diff',
            '/markdown',
            '/texttoimg',
            '/webinfo',
            '/bar',
            '/line',
            '/pie',
            '/scatter',
            '/coin',
            '/dice',
            '/textremoveduplicate',
            '/imgcut',
            '/httpstatuscode',
            '/jwt',
            '/htmlentity',
            '/colorpicker',
            '/asciiwordpic',
            '/jsforamt',
            '/htmlformat',
            '/cssformat',
            '/textedit',
            '/base64',
            '/baseconverter',
            '/storageconverter',
            '/hashcalculator',
            '/xmlformat',
            '/sqlformat',
            '/textreplace',
            '/textworkflow',
            '/emoji',
            '/wordfrequency',
            '/wordcloud',
            '/lottery',
            '/rockpaperscissors',
            '/wheel',
            '/imagecolorpicker',
            '/pomodoro',
            '/calculator',
            '/reactiontest',
            '/m3u8player',
            '/imagewatermark',
            '/colorpalette',
            '/about'
        ],
        // network: true,
        // removeStyle: true
    })
}